AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Stock Lambda Producer - Fetches stock prices and sends to Kinesis'

Parameters:
  FinnhubApiKey:
    Type: String
    Description: API key for Finnhub stock data service
    NoEcho: true
  
  KinesisStreamName:
    Type: String
    Default: stock-prices-stream
    Description: Name of the Kinesis Data Stream
  
  PollingIntervalSeconds:
    Type: Number
    Default: 5
    Description: How often to fetch stock prices (in seconds) - Step Functions supports any interval
    MinValue: 1
    MaxValue: 3600
    ConstraintDescription: Must be between 1 and 3600 seconds (1 second to 1 hour)
  
  EnforceMarketHours:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Whether to enforce market hours (true/false)
  
  TestMode:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    Description: Enable test mode to bypass market hours check (true/false)
  
  UseSecretsManager:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Use AWS Secrets Manager to store API key (recommended)
  
  StockSymbols:
    Type: String
    Default: 'AAPL,GOOGL,MSFT,AMZN,TSLA,META,NVDA,NFLX'
    Description: Comma-separated list of stock symbols to track

Conditions:
  UseSecretsManagerCondition: !Equals [!Ref UseSecretsManager, 'true']

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.11

Resources:
  FinnhubApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Condition: UseSecretsManagerCondition
    Properties:
      Name: finnhub-api-key
      Description: Finnhub API key for stock data access
      SecretString: !Ref FinnhubApiKey
      
  StockPricesStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Ref KinesisStreamName
      ShardCount: 1
      RetentionPeriodHours: 24
      
  StockLambdaProducer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          FINNHUB_API_KEY: !If [UseSecretsManagerCondition, '', !Ref FinnhubApiKey]
          KINESIS_STREAM_NAME: !Ref KinesisStreamName
          POLLING_INTERVAL_SECONDS: !Ref PollingIntervalSeconds
          ENFORCE_MARKET_HOURS: !Ref EnforceMarketHours
          TEST_MODE: !Ref TestMode
          USE_SECRETS_MANAGER: !Ref UseSecretsManager
          SECRET_NAME: !If [UseSecretsManagerCondition, !Ref FinnhubApiKeySecret, '']
          STOCK_SYMBOLS: !Ref StockSymbols
      Policies:
        - KinesisCrudPolicy:
            StreamName: !Ref KinesisStreamName
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
            - !If
              - UseSecretsManagerCondition
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref FinnhubApiKeySecret
              - !Ref AWS::NoValue

  # Step Functions resources for sub-minute execution
  StepFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt StockLambdaProducer.Arn
        - PolicyName: LoggingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                Resource: '*'

  EventBridgeExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StartStepFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Ref StockPriceStateMachine

  StockPriceStateMachine:
    Type: AWS::StepFunctions::StateMachine
    DependsOn: StepFunctionLogGroup
    Properties:
      StateMachineName: !Sub '${AWS::StackName}-stock-price-collector'
      DefinitionString: !Sub |
        {
          "Comment": "Stock price collection with configurable intervals (supports sub-minute)",
          "StartAt": "InitializeExecution",
          "States": {
            "InitializeExecution": {
              "Type": "Pass",
              "Result": {
                "executionCount": 0,
                "maxExecutions": 8640
              },
              "Next": "FetchStockPrices"
            },
            "FetchStockPrices": {
              "Type": "Task",
              "Resource": "${StockLambdaProducer.Arn}",
              "Next": "IncrementCounter",
              "ResultPath": "$.lambdaResult",
              "Retry": [
                {
                  "ErrorEquals": ["States.ALL"],
                  "IntervalSeconds": 2,
                  "MaxAttempts": 3,
                  "BackoffRate": 2.0
                }
              ],
              "Catch": [
                {
                  "ErrorEquals": ["States.ALL"],
                  "Next": "IncrementCounter",
                  "ResultPath": "$.lambdaError"
                }
              ]
            },
            "IncrementCounter": {
              "Type": "Pass",
              "Parameters": {
                "executionCount.$": "States.MathAdd($.executionCount, 1)",
                "maxExecutions.$": "$.maxExecutions",
                "lambdaResult.$": "$.lambdaResult",
                "lambdaError.$": "$.lambdaError"
              },
              "Next": "CheckExecutionLimit"
            },
            "CheckExecutionLimit": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.executionCount",
                  "NumericGreaterThanEquals": 8640,
                  "Next": "ExecutionComplete"
                }
              ],
              "Default": "WaitForNextRun"
            },
            "WaitForNextRun": {
              "Type": "Wait",
              "Seconds": ${PollingIntervalSeconds},
              "Next": "FetchStockPrices"
            },
            "WaitAfterError": {
              "Type": "Wait",
              "Seconds": 60,
              "Next": "IncrementCounter"
            },
            "ExecutionComplete": {
              "Type": "Succeed",
              "Comment": "Execution completed - controller will restart if needed"
            }
          }
        }
      RoleArn: !GetAtt StepFunctionExecutionRole.Arn
      LoggingConfiguration:
        Level: ERROR
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StepFunctionLogGroup.Arn

  StepFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/stepfunctions/${AWS::StackName}-stock-price-collector'
      RetentionInDays: 7

  # Smart controller Lambda that starts/stops Step Function based on market hours
  StepFunctionControllerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: step_function_controller.lambda_handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref StockPriceStateMachine
          ENFORCE_MARKET_HOURS: !Ref EnforceMarketHours
          TEST_MODE: !Ref TestMode
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - states:ListExecutions
                - states:StartExecution
                - states:StopExecution
                - states:DescribeExecution
              Resource: !Ref StockPriceStateMachine
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'

  # EventBridge rule to check and control Step Function every 30 minutes
  StepFunctionControllerRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Smart controller for Step Function - starts/stops based on market hours"
      ScheduleExpression: "rate(30 minutes)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt StepFunctionControllerFunction.Arn
          Id: "StepFunctionControllerTarget"

  # Permission for EventBridge to invoke the controller Lambda
  StepFunctionControllerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StepFunctionControllerFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt StepFunctionControllerRule.Arn

  StockLambdaProducerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${StockLambdaProducer}'
      RetentionInDays: 7

Outputs:
  StockLambdaProducerFunction:
    Description: Stock Lambda Producer Function ARN
    Value: !GetAtt StockLambdaProducer.Arn
    
  KinesisStreamArn:
    Description: Kinesis Data Stream ARN
    Value: !GetAtt StockPricesStream.Arn
    
  KinesisStreamName:
    Description: Kinesis Data Stream Name
    Value: !Ref StockPricesStream
    
  StepFunctionArn:
    Description: Step Function State Machine ARN
    Value: !Ref StockPriceStateMachine
    
  StepFunctionName:
    Description: Step Function State Machine Name
    Value: !Sub '${AWS::StackName}-stock-price-collector'